### ISSUE TITLE
Gerber file incomplete?

### ISSUE THREAD

**Issue by eburman** [connornishijima/Pixie#2]
The gerber files provided in "extras" doesn't seem to include any drill files.

**Comment by connornishijima** [comment]
Sorry about that! The extras/hardware/Gerbers folder has just been updated with Excellon files!

**Comment by eburman** [comment]
Thank you for including the drill files. Unfortunately the drill holes don't all match up. JLCPCB is rejecting the Gerber files because not all of the drill holes match up. So close far.

![db7ab62b12d34a5aab69660a010358bc](https://user-images.githubusercontent.com/42524071/88876319-e0540d00-d1d7-11ea-80ea-c0f30bc3c35a.png)
