### ISSUE TITLE
Drill files are a bit off

### ISSUE THREAD

**Issue by eburman** [connornishijima/Pixie#3]
Hi, I'm very sorry to be such a drudge but the drill files that you just posted seem to be a bit off. It looks like some of the holes don't match up with where they're supposed to be (some of the vias?). I submitted the Gerber files along with the newly included drill file to JLCPCB but they rejected my order due to the mismatch. They sent me this diagram to show what they thought were errors:
![db7ab62b12d34a5aab69660a010358bc](https://user-images.githubusercontent.com/42524071/88936547-e37ee580-d237-11ea-9257-5b974c97f9e9.png)

**Comment by connornishijima** [comment]
Sorry about that! The drill file added was from the beta version, not the final. It has been fixed/reuploaded!
