### ISSUE TITLE
Schematic overview

### ISSUE THREAD

**Issue by BenRoe** [connornishijima/Pixie#4]
Hello,
first thank you for this great project.
I am working on a calculator and your pixie seems to be a great way for the digits, but it would be more compact to put everything on the pcb.
Is it possible that you share the schematic of the pixie pcb?

**Comment by connornishijima** [comment]
It is in the Pixie Datasheet, page 7: https://connornishijima.github.io/Pixie/extras/datasheet.html?page=7

**Comment by BenRoe** [comment]
Thank you.
