### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by yuhanwen2013** [connornishijima/Pixie#6]
I would like to ask, which two types of capacitors should be selected ，thanks

**Comment by eburman** [comment]
Yes. I was wondering the same.

**Comment by vascobarbosa** [comment]
same here

**Comment by vascobarbosa** [comment]
got them working

1 x 10uf cap

**Comment by eburman** [comment]
Thanks vascobarbosa!

**Comment by yuhanwen2013** [comment]
cool！
