### ISSUE TITLE
I guess this project is abandoned

### ISSUE THREAD

**Issue by vascobarbosa** [connornishijima/Pixie#7]
I ordered the the pcbs from jlpcb
got the hardware from mouser ( led driver and attinys45 )

I am getting some troubles making them work.

I can make a double digit countdown , hardcoded on the attiny

but can't make the firmware work, working on that.
made this thread because there's no answer from 
Lixie Labs ( tried github, twitter and tindie store ) so 
I guess I'm reverse engineering this , and place my findings here

feel free to contribute please

**Comment by vascobarbosa** [comment]
so, this code works, if u want to try the connection between attiny45 and the led driver:


`#include <avr/io.h>

#define I2C_TIMEOUT 10000
#define I2C_FASTMODE 1    // 400kHz
#define I2C_PULLUP 1      // Enable pullups to avoid more passives on board
#define I2C_NOINTERRUPT 1 // No interrupts allowed when sending I2C data
#define SDA_PORT PORTB
#define SCL_PORT PORTB
#define SDA_PIN 0         // PB0
#define SCL_PIN 2         // PB2
#define dd 100

#include <SoftI2CMaster.h> // Include I2C Library
#define I2C_7BITADDR 0x63  // Each Pixie manages it's own display driver at a hard-coded I2C address

const uint8_t CLK_pin     = 1; //PB1
const uint8_t DAT_IN_pin  = 3; //PB3
const uint8_t DAT_OUT_pin = 4; //PB4

byte disp[10];            // Display buffer

byte row[7];
byte rowindex = 0;

byte col[60] = {                     // even digits (2,4,6) have column bit map for each column of 5x7 matrix
    0x00, 0x00, 0x00, 0x00, 0x00,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x3E, 0x51, 0x49, 0x45, 0x3E, // 0        10
    0x00, 0x42, 0x7F, 0x40, 0x00, // 1        11
    0x42, 0x61, 0x51, 0x49, 0x46, // 2        12
    0x21, 0x41, 0x45, 0x4B, 0x31, // 3        13
    0x18, 0x14, 0x12, 0x7F, 0x10, // 4        14
    0x27, 0x45, 0x45, 0x45, 0x39, // 5        15
    0x3C, 0x4A, 0x49, 0x49, 0x30, // 6        16
    0x01, 0x71, 0x09, 0x05, 0x03, // 7        17
    0x36, 0x49, 0x49, 0x49, 0x36, // 8        18
    0x06, 0x49, 0x49, 0x29, 0x1E  // 9        19// #        03
    };



void setup() {
  // put your setup code here, to run once:
  disp[4] = 10;
  delay(10); // Not sure why this works. (Maybe unstable connections when first powered?) Please figure it out.
//  pinMode(CLK_pin,     INPUT);
//  pinMode(DAT_IN_pin,  INPUT);
//  pinMode(DAT_OUT_pin, OUTPUT);

   i2c_init();       // Init bitbang I2C
   init_display();   // Init idsplay driver
   for(int i = 0;i<2;i++){
     Dwrite(1,i);
     delay(dd);
     Dwrite(0,i);
     delay(dd);
     Dwrite(1,i);
     delay(dd);    
     Dwrite(0,i);
     delay(dd);   
   }
}

int i = 0;

void loop() {
  int f = i/10;
  int r = i%10;
  Dwrite(2+f,0);
  Dwrite(2+r,1);
  delay(dd); 
  i++;
  if(i>99) i=0;
}

void update_display(){

}



void init_display() {
  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0xFF);                  // write to reset register
  i2c_write(0x00);                  // write row data - sets dual display mode
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x00);                  // write to configuration register
  i2c_write(0x19);                  // write row data - sets dual display mode
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x0D);                  // write to LIGHTING EFFECT REGISTER
  i2c_write(0x09);             // sets row current to 40mA
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x19);                  // write to PWM REGISTER
  i2c_write(0x80);             // sets pwm to 128 (max)
  i2c_stop();
}

void Dwrite(byte x, int d){
    i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c
    // first digit
    if(d == 0){
      i2c_write(0x0E);                 // write to DIGIT 1
     for (int coly =0; coly<5; coly++ ){
        i2c_write (col[x*5 + coly]);                 //write row data 
      }
      }else{
        //second digit
        coltorowconv(x);
         i2c_write(0x01);                 // write to DIGIT 1

      for (int rowx = 0; rowx<7; rowx++ ){
        i2c_write (row[rowx]); 
      }
    }
    i2c_stop();

    i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c
    i2c_write(0x0c);
    i2c_write(0xff);
    i2c_stop();      
    
  }


  void coltorowconv(byte digit) {                   // convert column dot matrix to row map

      for (rowindex = 0; rowindex < 7; rowindex++){
            row[rowindex] = 0;
                row[rowindex] =  (bitRead(col[digit * 5 + 0], rowindex) * 1)
                                +(bitRead(col[digit * 5 + 1], rowindex) * 2)
                                +(bitRead(col[digit * 5 + 2], rowindex) * 4)
                                +(bitRead(col[digit * 5 + 3], rowindex) * 8)
                                +(bitRead(col[digit * 5 + 4], rowindex) * 16);

             }    // end rowindex loop
} 

`

**Comment by vascobarbosa** [comment]
This is a firmware code to test a single pcb ( 2 digits ) 
with a countdown. To check if the soldering and connection
is working

----------------------------------------------


#include <avr/io.h>

#define I2C_TIMEOUT 10000
#define I2C_FASTMODE 1    // 400kHz
#define I2C_PULLUP 1      // Enable pullups to avoid more passives on board
#define I2C_NOINTERRUPT 1 // No interrupts allowed when sending I2C data
#define SDA_PORT PORTB
#define SCL_PORT PORTB
#define SDA_PIN 0         // PB0
#define SCL_PIN 2         // PB2
#define dd 100

#include <SoftI2CMaster.h> // Include I2C Library
#define I2C_7BITADDR 0x63  // Each Pixie manages it's own display driver at a hard-coded I2C address

const uint8_t CLK_pin     = 1; //PB1
const uint8_t DAT_IN_pin  = 3; //PB3
const uint8_t DAT_OUT_pin = 4; //PB4

byte disp[10];            // Display buffer

byte row[7];
byte rowindex = 0;

byte col[60] = {                     // even digits (2,4,6) have column bit map for each column of 5x7 matrix
    0x00, 0x00, 0x00, 0x00, 0x00,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x3E, 0x51, 0x49, 0x45, 0x3E, // 0        10
    0x00, 0x42, 0x7F, 0x40, 0x00, // 1        11
    0x42, 0x61, 0x51, 0x49, 0x46, // 2        12
    0x21, 0x41, 0x45, 0x4B, 0x31, // 3        13
    0x18, 0x14, 0x12, 0x7F, 0x10, // 4        14
    0x27, 0x45, 0x45, 0x45, 0x39, // 5        15
    0x3C, 0x4A, 0x49, 0x49, 0x30, // 6        16
    0x01, 0x71, 0x09, 0x05, 0x03, // 7        17
    0x36, 0x49, 0x49, 0x49, 0x36, // 8        18
    0x06, 0x49, 0x49, 0x29, 0x1E  // 9        19// #        03
    };



void setup() {
  // put your setup code here, to run once:
  disp[4] = 10;
  delay(10); // Not sure why this works. (Maybe unstable connections when first powered?) Please figure it out.
//  pinMode(CLK_pin,     INPUT);
//  pinMode(DAT_IN_pin,  INPUT);
//  pinMode(DAT_OUT_pin, OUTPUT);

   i2c_init();       // Init bitbang I2C
   init_display();   // Init idsplay driver
   for(int i = 0;i<2;i++){
     Dwrite(1,i);
     delay(dd);
     Dwrite(0,i);
     delay(dd);
     Dwrite(1,i);
     delay(dd);    
     Dwrite(0,i);
     delay(dd);   
   }
}

int i = 0;

void loop() {
  int f = i/10;
  int r = i%10;
  Dwrite(2+f,0);
  Dwrite(2+r,1);
  delay(dd); 
  i++;
  if(i>99) i=0;
}

void update_display(){

}



void init_display() {
  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0xFF);                  // write to reset register
  i2c_write(0x00);                  // write row data - sets dual display mode
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x00);                  // write to configuration register
  i2c_write(0x19);                  // write row data - sets dual display mode
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x0D);                  // write to LIGHTING EFFECT REGISTER
  i2c_write(0x09);             // sets row current to 40mA
  i2c_stop();

  i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c address 0x63
  i2c_write(0x19);                  // write to PWM REGISTER
  i2c_write(0x80);             // sets pwm to 128 (max)
  i2c_stop();
}

void Dwrite(byte x, int d){
    i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c
    // first digit
    if(d == 0){
      i2c_write(0x0E);                 // write to DIGIT 1
     for (int coly =0; coly<5; coly++ ){
        i2c_write (col[x*5 + coly]);                 //write row data 
      }
      }else{
        //second digit
        coltorowconv(x);
         i2c_write(0x01);                 // write to DIGIT 1

      for (int rowx = 0; rowx<7; rowx++ ){
        i2c_write (row[rowx]); 
      }
    }
    i2c_stop();

    i2c_start_wait((I2C_7BITADDR << 1) | I2C_WRITE); //  write i2c
    i2c_write(0x0c);
    i2c_write(0xff);
    i2c_stop();      
    
  }


  void coltorowconv(byte digit) {                   // convert column dot matrix to row map

      for (rowindex = 0; rowindex < 7; rowindex++){
            row[rowindex] = 0;
                row[rowindex] =  (bitRead(col[digit * 5 + 0], rowindex) * 1)
                                +(bitRead(col[digit * 5 + 1], rowindex) * 2)
                                +(bitRead(col[digit * 5 + 2], rowindex) * 4)
                                +(bitRead(col[digit * 5 + 3], rowindex) * 8)
                                +(bitRead(col[digit * 5 + 4], rowindex) * 16);

             }    // end rowindex loop
}

**Comment by eburman** [comment]
I also have the PCB's and all the parts but I haven't gotten around to building it. I have so many projects and so little time. Maybe I can motivate myself to get it together. It looks like you are way ahead of me.

**Comment by vascobarbosa** [comment]
I'm at the point of reading about stuff and found out that arduino as a programmer has diferent
results on windows and on mac as explained on this thread : 

https://forum.arduino.cc/index.php?topic=216663.0

so now, I'm scavenging a windows machine to test this theory.

**Comment by vascobarbosa** [comment]
ok, Got them working

with attiny85, 
1 - 10uf cap

<img width="558" alt="Screen Shot 2021-03-10 at 22 44 26" src="https://user-images.githubusercontent.com/2828849/110708154-31a68f00-81f2-11eb-89ca-89a66f32e6f1.png">

**Comment by eburman** [comment]
vascobarbosa....Beautiful! Thank you so much for sharing all the detailed information that you discovered!

**Comment by vascobarbosa** [comment]
I did made them work in osx also, so I guess the windows doesnt matter at all
